<?php

namespace AMK\SchemaCore\Schema;

defined('ABSPATH') || exit;

class SchemaTemplateContract {

    public static function type_options() {
        return [
            // Entity templates. The final Schema.org @type may be a single value
            // or an array generated by GlobalSettings / DataResolver.
            // Keep the internal template type as "organization" for the main
            // site owner/business node, even when the final @type becomes
            // Organization + Store + OnlineStore.
            'organization'  => __('Organization Entity - Organization / brand / store', 'amk-schema-core'),
            'onlinestore'   => __('OnlineStore - Standalone online store', 'amk-schema-core'),
            'store'         => __('Store - Standalone physical store', 'amk-schema-core'),
            'localbusiness' => __('LocalBusiness - Standalone local business', 'amk-schema-core'),

            // Web/page templates.
            'website'       => __('WebSite - Website', 'amk-schema-core'),
            'webpage'       => __('WebPage - Page', 'amk-schema-core'),
            'aboutpage'     => __('AboutPage - About page', 'amk-schema-core'),
            'contactpage'   => __('ContactPage - Contact page', 'amk-schema-core'),
            'article'       => __('Article - Article', 'amk-schema-core'),
            'product'       => __('Product - Product', 'amk-schema-core'),
            'productgroup'  => __('ProductGroup - Variable product group', 'amk-schema-core'),
            'collection'    => __('CollectionPage - Archive / category', 'amk-schema-core'),
            'breadcrumb'    => __('BreadcrumbList - Breadcrumb trail', 'amk-schema-core'),
            'itemlist'      => __('ItemList - Item list', 'amk-schema-core'),
            'navigation'    => __('SiteNavigationElement - Site menu', 'amk-schema-core'),
            'custom'        => __('Custom - Custom', 'amk-schema-core'),
        ];
    }

    public static function scope_options() {
        return [
            'global'           => __('Global / all pages', 'amk-schema-core'),
            'home'             => __('Home page', 'amk-schema-core'),
            'page'             => __('Page / generic page', 'amk-schema-core'),
            'single_post'      => __('Single post', 'amk-schema-core'),
            'product'          => __('WooCommerce product', 'amk-schema-core'),
            'product_category' => __('Product category', 'amk-schema-core'),
            'product_tag'      => __('Product tag', 'amk-schema-core'),
            'collection'       => __('Shop / product archive / collection', 'amk-schema-core'),
            'blog_archive'     => __('Blog archive', 'amk-schema-core'),
            'category_archive' => __('Post category archive', 'amk-schema-core'),
            'tag_archive'      => __('Post tag archive', 'amk-schema-core'),
            'author_archive'   => __('Author archive', 'amk-schema-core'),
            'archive'          => __('Generic archive', 'amk-schema-core'),
            'search'           => __('Search results', 'amk-schema-core'),
            '404'              => __('404 page', 'amk-schema-core'),
            'default'          => __('Default / fallback', 'amk-schema-core'),
        ];
    }

    public static function normalize_type($type) {
        $type = self::safe_key($type);

        $aliases = [
            'organization'     => 'organization',
            'org'              => 'organization',
            'brand'            => 'organization',
            'business_entity'  => 'organization',
            'business-entity'  => 'organization',
            'organizationstore' => 'organization',
            'organization_store' => 'organization',
            'organization-store' => 'organization',
            'hybrid_store'     => 'organization',
            'hybrid-store'     => 'organization',

            'onlinestore'      => 'onlinestore',
            'online_store'     => 'onlinestore',
            'online-store'     => 'onlinestore',

            'store'            => 'store',

            'localbusiness'    => 'localbusiness',
            'local_business'   => 'localbusiness',
            'local-business'   => 'localbusiness',

            'website'          => 'website',
            'web_site'         => 'website',
            'web-site'         => 'website',

            'webpage'          => 'webpage',
            'web_page'         => 'webpage',
            'web-page'         => 'webpage',

            'aboutpage'        => 'aboutpage',
            'about_page'       => 'aboutpage',
            'about-page'       => 'aboutpage',
            'about'            => 'aboutpage',

            'contactpage'      => 'contactpage',
            'contact_page'     => 'contactpage',
            'contact-page'     => 'contactpage',
            'contact'          => 'contactpage',

            'article'          => 'article',
            'post'             => 'article',

            'product'          => 'product',

            'productgroup'     => 'productgroup',
            'product_group'    => 'productgroup',
            'product-group'    => 'productgroup',
            'variable_product' => 'productgroup',
            'variable-product' => 'productgroup',

            'collection'       => 'collection',
            'collection_page'  => 'collection',
            'collection-page'  => 'collection',
            'collectionpage'   => 'collection',

            'breadcrumb'       => 'breadcrumb',
            'breadcrumb_list'  => 'breadcrumb',
            'breadcrumb-list'  => 'breadcrumb',
            'breadcrumblist'   => 'breadcrumb',

            'itemlist'         => 'itemlist',
            'item_list'        => 'itemlist',
            'item-list'        => 'itemlist',

            'navigation'       => 'navigation',
            'site_navigation'  => 'navigation',
            'site-navigation'  => 'navigation',
            'sitenavigation'   => 'navigation',
            'site_nav'         => 'navigation',
            'site-nav'         => 'navigation',
            'sitenavigationelement' => 'navigation',

            'custom'           => 'custom',
        ];

        $lookup_key = str_replace('-', '_', $type);

        if (isset($aliases[$type])) {
            return $aliases[$type];
        }

        if (isset($aliases[$lookup_key])) {
            return $aliases[$lookup_key];
        }

        return array_key_exists($type, self::type_options()) ? $type : 'custom';
    }

    public static function normalize_scope($scope) {
        $scope = self::safe_key($scope);

        $aliases = [
            'global'               => 'global',
            'sitewide'             => 'global',
            'all'                  => 'global',

            'home'                 => 'home',
            'front_page'           => 'home',
            'front-page'           => 'home',
            'homepage'             => 'home',

            'page'                 => 'page',
            'singular'             => 'page',
            'single'               => 'page',
            'webpage'              => 'page',

            'post'                 => 'single_post',
            'single_post'          => 'single_post',
            'single-post'          => 'single_post',
            'singlepost'           => 'single_post',

            'product'              => 'product',
            'single_product'       => 'product',
            'single-product'       => 'product',

            'product_category'     => 'product_category',
            'product-category'     => 'product_category',
            'product_cat'          => 'product_category',

            'product_tag'          => 'product_tag',
            'product-tag'          => 'product_tag',

            'shop'                 => 'collection',
            'collection'           => 'collection',
            'product_archive'      => 'collection',
            'product-archive'      => 'collection',
            'collection_page'      => 'collection',
            'collection-page'      => 'collection',

            'blog_archive'         => 'blog_archive',
            'blog-archive'         => 'blog_archive',
            'blog'                 => 'blog_archive',

            'category'             => 'category_archive',
            'category_archive'     => 'category_archive',
            'category-archive'     => 'category_archive',

            'tag'                  => 'tag_archive',
            'tag_archive'          => 'tag_archive',
            'tag-archive'          => 'tag_archive',

            'author'               => 'author_archive',
            'author_archive'       => 'author_archive',
            'author-archive'       => 'author_archive',

            'archive'              => 'archive',
            'generic_archive'      => 'archive',

            'search'               => 'search',

            '404'                  => '404',
            'not_found'            => '404',
            'not-found'            => '404',
            'notfound'             => '404',
            '404_page'             => '404',

            'default'              => 'default',
            'fallback'             => 'default',
        ];

        $lookup_key = str_replace('-', '_', $scope);

        if (isset($aliases[$scope])) {
            return $aliases[$scope];
        }

        if (isset($aliases[$lookup_key])) {
            return $aliases[$lookup_key];
        }

        return array_key_exists($scope, self::scope_options()) ? $scope : 'global';
    }

    public static function type_label($type) {
        $type    = self::normalize_type($type);
        $options = self::type_options();

        return isset($options[$type]) ? $options[$type] : $type;
    }

    public static function scope_label($scope) {
        $scope   = self::normalize_scope($scope);
        $options = self::scope_options();

        return isset($options[$scope]) ? $options[$scope] : $scope;
    }

    public static function schema_org_type($type) {
        $type = self::normalize_type($type);

        $map = [
            'organization'  => 'Organization',
            'onlinestore'   => 'OnlineStore',
            'store'         => 'Store',
            'localbusiness' => 'LocalBusiness',
            'website'       => 'WebSite',
            'webpage'       => 'WebPage',
            'aboutpage'     => 'AboutPage',
            'contactpage'   => 'ContactPage',
            'article'       => 'Article',
            'product'       => 'Product',
            'productgroup'  => 'ProductGroup',
            'collection'    => 'CollectionPage',
            'breadcrumb'    => 'BreadcrumbList',
            'itemlist'      => 'ItemList',
            'navigation'    => 'SiteNavigationElement',
            'custom'        => 'Thing',
        ];

        return isset($map[$type]) ? $map[$type] : 'Thing';
    }

    /**
     * Main entity template types.
     *
     * These are the internal template types that may represent the site owner
     * or business entity. The final Schema.org @type is resolved separately by
     * organization_types, so this method is intentionally about internal
     * grouping, not the final JSON-LD @type.
     *
     * @return array
     */
    public static function organization_like_types() {
        return [
            'organization',
            'onlinestore',
            'store',
            'localbusiness',
        ];
    }

    /**
     * Check whether an internal template type is organization/business-like.
     *
     * @param string $type
     * @return bool
     */
    public static function is_organization_like_type($type) {
        return in_array(self::normalize_type($type), self::organization_like_types(), true);
    }

    public static function normalize_template_row($template) {
        if (!is_array($template)) {
            return [];
        }

        if (isset($template['type'])) {
            $template['type'] = self::normalize_type($template['type']);
        }

        if (isset($template['scope'])) {
            $template['scope'] = self::normalize_scope($template['scope']);
        }

        return $template;
    }

    private static function safe_key($value) {
        if (!is_string($value) && !is_numeric($value)) {
            return '';
        }

        $value = trim((string) $value);

        if ($value === '') {
            return '';
        }

        if (function_exists('sanitize_key')) {
            return sanitize_key($value);
        }

        $value = strtolower($value);
        $value = preg_replace('/[^a-z0-9_\-]/', '', $value);

        return is_string($value) ? $value : '';
    }
}