<?php

defined('ABSPATH') || exit;

/**
 * Default Schema Templates
 *
 * Important:
 * - `type` is internal plugin type, always lowercase.
 * - `scope` is internal normalized scope.
 * - `schema_json.@type` is real Schema.org type.
 * - `replace_on_seed = 1` allows seed-defaults.php to update old default templates.
 * - Home Page Schema intentionally has no breadcrumb reference.
 * - Store-only fields are added at runtime only when the resolved entity type supports them.
 */

return [

    [
        'name'            => 'Organization / OnlineStore + Local Store Schema',
        'type'            => 'organization',
        'scope'           => 'global',
        'status'          => 'active',
        'priority'        => 100,
        'override'        => 0,
        'replace_on_seed' => 1,
        'legacy_names'     => [
            'Organization / Store Schema',
            'Organization / OnlineStore Schema',
        ],

        'schema_json' => [
            '@context' => 'https://schema.org',
            '@graph'   => [
                [
                    '@type'                   => '{{organization_types}}',
                    '@id'                     => '{{organization_id}}',
                    'name'                    => '{{organization_name}}',
                    'legalName'               => '{{organization_legal_name}}',
                    'alternateName'           => '{{organization_alternate_name}}',
                    'url'                     => '{{organization_url}}',
                    'description'             => '{{organization_description}}',
                    'logo'                    => '{{organization_logo}}',
                    'image'                   => '{{organization_image}}',
                    'telephone'               => '{{organization_telephone}}',
                    'email'                   => '{{organization_email}}',
                    'contactPoint'            => '{{organization_contact_point}}',
                    'sameAs'                  => '{{organization_same_as}}',
                    'foundingDate'            => '{{organization_founding_date}}',
                    'taxID'                   => '{{organization_tax_id}}',
                    'vatID'                   => '{{organization_vat_id}}',
                                        'acceptedPaymentMethod'   => '{{organization_payment_accepted}}',
                    'hasMerchantReturnPolicy' => '{{merchant_return_policy}}',
                    'hasShippingService'      => '{{shipping_service}}',
                ],
                '{{local_store_schema}}',
            ],
        ],

        'bindings' => [
            'organization_types'               => 'organization_types',
            'organization_id'                  => 'organization_id',
            'organization_name'                => 'organization_name',
            'organization_legal_name'          => 'organization_legal_name',
            'organization_alternate_name'      => 'organization_alternate_name',
            'organization_url'                 => 'organization_url',
            'organization_description'         => 'organization_description',
            'organization_logo'                => 'organization_logo',
            'organization_image'               => 'organization_image',
            'organization_telephone'           => 'organization_telephone',
            'organization_email'               => 'organization_email',
            'organization_contact_point'       => 'organization_contact_point',
            'organization_same_as'             => 'organization_same_as',
            'organization_founding_date'       => 'organization_founding_date',
            'organization_tax_id'              => 'organization_tax_id',
            'organization_vat_id'              => 'organization_vat_id',
            'organization_currencies_accepted' => 'organization_currencies_accepted',
            'organization_payment_accepted'    => 'organization_payment_accepted',
            'merchant_return_policy'           => 'merchant_return_policy',
            'shipping_service'                 => 'shipping_service',
            'local_store_schema'               => 'local_store_schema',
        ],

        'conditions' => [],
    ],

    [
        'name'            => 'WebSite Schema',
        'type'            => 'website',
        'scope'           => 'global',
        'status'          => 'active',
        'priority'        => 90,
        'override'        => 0,
        'replace_on_seed' => 1,

        'schema_json' => [
            '@context'        => 'https://schema.org',
            '@type'           => 'WebSite',
            '@id'             => '{{website_id}}',
            'name'            => '{{site_name}}',
            'url'             => '{{site_url}}',
            'description'     => '{{site_description}}',
            'publisher'       => [
                '@id' => '{{organization_id}}',
            ],
            'inLanguage'      => '{{language}}',
            'potentialAction' => [
                '@type'       => 'SearchAction',
                'target'      => '{{website_search_target}}',
                'query-input' => 'required name=search_term_string',
            ],
        ],

        'bindings' => [
            'website_id'            => 'website_id',
            'site_name'             => 'site_name',
            'site_url'              => 'site_url',
            'site_description'      => 'site_description',
            'organization_id'       => 'organization_id',
            'language'              => 'language',
            'website_search_target' => 'website_search_target',
        ],

        'conditions' => [
            [
                'data_key' => 'site_description',
                'field'    => 'site_description',
                'operator' => 'empty',
                'action'   => 'remove',
                'path'     => 'description',
                'priority' => 10,
                'status'   => 'active',
            ],
            [
                'data_key' => 'language',
                'field'    => 'language',
                'operator' => 'empty',
                'action'   => 'remove',
                'path'     => 'inLanguage',
                'priority' => 20,
                'status'   => 'active',
            ],
            [
                'data_key' => 'website_search_target',
                'field'    => 'website_search_target',
                'operator' => 'empty',
                'action'   => 'remove',
                'path'     => 'potentialAction',
                'priority' => 30,
                'status'   => 'active',
            ],
        ],
    ],

    [
        'name'            => 'WebPage Schema',
        'type'            => 'webpage',
        'scope'           => 'page',
        'status'          => 'active',
        'priority'        => 70,
        'override'        => 0,
        'replace_on_seed' => 1,

        'schema_json' => [
            '@context'    => 'https://schema.org',
            '@type'       => '{{webpage_type}}',
            '@id'         => '{{webpage_id}}',
            'name'        => '{{title}}',
            'description' => '{{description}}',
            'url'         => '{{url}}',
            'isPartOf'    => [
                '@id' => '{{website_id}}',
            ],
            'publisher'   => [
                '@id' => '{{organization_id}}',
            ],
            'about'       => '{{webpage_about}}',
            'mainEntity'  => '{{webpage_main_entity}}',
            'breadcrumb'  => [
                '@id' => '{{breadcrumb_id}}',
            ],
            'inLanguage'  => '{{language}}',
        ],

        'bindings' => [
            'webpage_type'    => 'webpage_type',
            'webpage_id'      => 'webpage_id',
            'title'           => 'title',
            'description'     => 'description',
            'url'             => 'url',
            'website_id'      => 'website_id',
            'organization_id' => 'organization_id',
            'webpage_about'   => 'webpage_about',
            'webpage_main_entity' => 'webpage_main_entity',
            'breadcrumb_id'   => 'breadcrumb_id',
            'language'        => 'language',
        ],

        'conditions' => [
            [
                'data_key' => 'description',
                'field'    => 'description',
                'operator' => 'empty',
                'action'   => 'remove',
                'path'     => 'description',
                'priority' => 10,
                'status'   => 'active',
            ],
            [
                'data_key' => 'webpage_about',
                'field'    => 'webpage_about',
                'operator' => 'empty',
                'action'   => 'remove',
                'path'     => 'about',
                'priority' => 20,
                'status'   => 'active',
            ],
            [
                'data_key' => 'webpage_main_entity',
                'field'    => 'webpage_main_entity',
                'operator' => 'empty',
                'action'   => 'remove',
                'path'     => 'mainEntity',
                'priority' => 25,
                'status'   => 'active',
            ],
            [
                'data_key' => 'breadcrumb_id',
                'field'    => 'breadcrumb_id',
                'operator' => 'empty',
                'action'   => 'remove',
                'path'     => 'breadcrumb',
                'priority' => 30,
                'status'   => 'active',
            ],
            [
                'data_key' => 'language',
                'field'    => 'language',
                'operator' => 'empty',
                'action'   => 'remove',
                'path'     => 'inLanguage',
                'priority' => 40,
                'status'   => 'active',
            ],
        ],
    ],

    [
        'name'            => 'Home Page Schema',
        'type'            => 'webpage',
        'scope'           => 'home',
        'status'          => 'active',
        'priority'        => 72,
        'override'        => 1,
        'replace_on_seed' => 1,

        'schema_json' => [
            '@context'    => 'https://schema.org',
            '@type'       => 'WebPage',
            '@id'         => '{{webpage_id}}',
            'name'        => '{{site_name}}',
            'description' => '{{site_description}}',
            'url'         => '{{home_url}}',
            'isPartOf'    => [
                '@id' => '{{website_id}}',
            ],
            'publisher'   => [
                '@id' => '{{organization_id}}',
            ],
            'inLanguage'  => '{{language}}',
        ],

        'bindings' => [
            'webpage_id'      => 'webpage_id',
            'site_name'       => 'site_name',
            'site_description'=> 'site_description',
            'home_url'        => 'home_url',
            'website_id'      => 'website_id',
            'organization_id' => 'organization_id',
            'language'        => 'language',
        ],

        'conditions' => [
            [
                'data_key' => 'site_description',
                'field'    => 'site_description',
                'operator' => 'empty',
                'action'   => 'remove',
                'path'     => 'description',
                'priority' => 10,
                'status'   => 'active',
            ],
            [
                'data_key' => 'language',
                'field'    => 'language',
                'operator' => 'empty',
                'action'   => 'remove',
                'path'     => 'inLanguage',
                'priority' => 20,
                'status'   => 'active',
            ],
        ],
    ],

    [
        'name'            => 'Article Schema',
        'type'            => 'article',
        'scope'           => 'single_post',
        'status'          => 'active',
        'priority'        => 75,
        'override'        => 0,
        'replace_on_seed' => 1,

        'schema_json' => [
            '@context'         => 'https://schema.org',
            '@type'            => 'Article',
            '@id'              => '{{url}}#article',
            'headline'         => '{{title}}',
            'description'      => '{{description}}',
            'image'            => '{{image}}',
            'datePublished'    => '{{date_published}}',
            'dateModified'     => '{{date_modified}}',
            'author'           => [
                '@type' => 'Person',
                'name'  => '{{author_name}}',
                'url'   => '{{author_url}}',
            ],
            'publisher'        => [
                '@id' => '{{organization_id}}',
            ],
            'mainEntityOfPage' => [
                '@type' => 'WebPage',
                '@id'   => '{{webpage_id}}',
            ],
            'inLanguage'       => '{{language}}',
        ],

        'bindings' => [
            'title'           => 'title',
            'description'     => 'description',
            'image'           => 'image',
            'date_published'  => 'date_published',
            'date_modified'   => 'date_modified',
            'author_name'     => 'author_name',
            'author_url'      => 'author_url',
            'organization_id' => 'organization_id',
            'webpage_id'      => 'webpage_id',
            'language'        => 'language',
            'url'             => 'url',
        ],

        'conditions' => [
            [
                'data_key' => 'description',
                'field'    => 'description',
                'operator' => 'empty',
                'action'   => 'remove',
                'path'     => 'description',
                'priority' => 10,
                'status'   => 'active',
            ],
            [
                'data_key' => 'image',
                'field'    => 'image',
                'operator' => 'empty',
                'action'   => 'remove',
                'path'     => 'image',
                'priority' => 20,
                'status'   => 'active',
            ],
            [
                'data_key' => 'date_published',
                'field'    => 'date_published',
                'operator' => 'empty',
                'action'   => 'remove',
                'path'     => 'datePublished',
                'priority' => 30,
                'status'   => 'active',
            ],
            [
                'data_key' => 'date_modified',
                'field'    => 'date_modified',
                'operator' => 'empty',
                'action'   => 'remove',
                'path'     => 'dateModified',
                'priority' => 40,
                'status'   => 'active',
            ],
            [
                'data_key' => 'author_name',
                'field'    => 'author_name',
                'operator' => 'empty',
                'action'   => 'remove',
                'path'     => 'author',
                'priority' => 50,
                'status'   => 'active',
            ],
            [
                'data_key' => 'language',
                'field'    => 'language',
                'operator' => 'empty',
                'action'   => 'remove',
                'path'     => 'inLanguage',
                'priority' => 60,
                'status'   => 'active',
            ],
        ],
    ],

    [
        'name'            => 'Product Schema',
        'type'            => 'product',
        'scope'           => 'product',
        'status'          => 'active',
        'priority'        => 80,
        'override'        => 0,
        'replace_on_seed' => 1,

        'schema_json' => [
            '@context'        => 'https://schema.org',
            '@type'           => '{{product_schema_type}}',
            '@id'             => '{{product_entity_id}}',
            'name'            => '{{name}}',
            'description'     => '{{description}}',
            'image'           => '{{images}}',
            'sku'             => '{{sku}}',
            'gtin'            => '{{gtin}}',
            'mpn'             => '{{mpn}}',
            'brand'           => '{{brand_schema}}',
            'offers'          => '{{product_offer}}',
            'productGroupID'  => '{{product_group_id_value}}',
            'variesBy'        => '{{product_varies_by}}',
            'hasVariant'      => '{{product_variants}}',
            'aggregateRating' => [
                '@type'       => 'AggregateRating',
                'ratingValue' => '{{rating_value}}',
                'reviewCount' => '{{review_count}}',
            ],
        ],

        'bindings' => [
            'product_schema_type'    => 'product_schema_type',
            'product_entity_id'      => 'product_entity_id',
            'name'                   => 'name',
            'description'            => 'description',
            'images'                 => 'images',
            'sku'                    => 'sku',
            'gtin'                   => 'gtin',
            'mpn'                    => 'mpn',
            'brand_schema'           => 'brand_schema',
            'product_offer'          => 'product_offer',
            'product_group_id_value' => 'product_group_id_value',
            'product_varies_by'      => 'product_varies_by',
            'product_variants'       => 'product_variants',
            'rating_value'           => 'rating_value',
            'review_count'           => 'review_count',
            'is_variable_product'    => 'is_variable_product',
        ],

        'conditions' => [
            [
                'data_key' => 'product_schema_type',
                'field'    => 'product_schema_type',
                'operator' => 'empty',
                'action'   => 'remove',
                'path'     => '@type',
                'priority' => 5,
                'status'   => 'active',
            ],
            [
                'data_key' => 'description',
                'field'    => 'description',
                'operator' => 'empty',
                'action'   => 'remove',
                'path'     => 'description',
                'priority' => 10,
                'status'   => 'active',
            ],
            [
                'data_key' => 'images',
                'field'    => 'images',
                'operator' => 'empty',
                'action'   => 'remove',
                'path'     => 'image',
                'priority' => 20,
                'status'   => 'active',
            ],
            [
                'data_key' => 'sku',
                'field'    => 'sku',
                'operator' => 'empty',
                'action'   => 'remove',
                'path'     => 'sku',
                'priority' => 30,
                'status'   => 'active',
            ],
            [
                'data_key' => 'gtin',
                'field'    => 'gtin',
                'operator' => 'empty',
                'action'   => 'remove',
                'path'     => 'gtin',
                'priority' => 40,
                'status'   => 'active',
            ],
            [
                'data_key' => 'mpn',
                'field'    => 'mpn',
                'operator' => 'empty',
                'action'   => 'remove',
                'path'     => 'mpn',
                'priority' => 50,
                'status'   => 'active',
            ],
            [
                'data_key' => 'brand_schema',
                'field'    => 'brand_schema',
                'operator' => 'empty',
                'action'   => 'remove',
                'path'     => 'brand',
                'priority' => 60,
                'status'   => 'active',
            ],
            [
                'data_key' => 'product_offer',
                'field'    => 'product_offer',
                'operator' => 'empty',
                'action'   => 'remove',
                'path'     => 'offers',
                'priority' => 70,
                'status'   => 'active',
            ],
            [
                'data_key' => 'is_variable_product',
                'field'    => 'is_variable_product',
                'operator' => 'not_equals',
                'value'    => 1,
                'action'   => 'remove',
                'path'     => 'productGroupID',
                'priority' => 80,
                'status'   => 'active',
            ],
            [
                'data_key' => 'is_variable_product',
                'field'    => 'is_variable_product',
                'operator' => 'not_equals',
                'value'    => 1,
                'action'   => 'remove',
                'path'     => 'variesBy',
                'priority' => 90,
                'status'   => 'active',
            ],
            [
                'data_key' => 'is_variable_product',
                'field'    => 'is_variable_product',
                'operator' => 'not_equals',
                'value'    => 1,
                'action'   => 'remove',
                'path'     => 'hasVariant',
                'priority' => 100,
                'status'   => 'active',
            ],
            [
                'data_key' => 'product_group_id_value',
                'field'    => 'product_group_id_value',
                'operator' => 'empty',
                'action'   => 'remove',
                'path'     => 'productGroupID',
                'priority' => 110,
                'status'   => 'active',
            ],
            [
                'data_key' => 'product_varies_by',
                'field'    => 'product_varies_by',
                'operator' => 'empty',
                'action'   => 'remove',
                'path'     => 'variesBy',
                'priority' => 120,
                'status'   => 'active',
            ],
            [
                'data_key' => 'product_variants',
                'field'    => 'product_variants',
                'operator' => 'empty',
                'action'   => 'remove',
                'path'     => 'hasVariant',
                'priority' => 130,
                'status'   => 'active',
            ],
            [
                'data_key' => 'rating_value',
                'field'    => 'rating_value',
                'operator' => 'empty',
                'action'   => 'remove',
                'path'     => 'aggregateRating',
                'priority' => 140,
                'status'   => 'active',
            ],
            [
                'data_key' => 'review_count',
                'field'    => 'review_count',
                'operator' => 'empty',
                'action'   => 'remove',
                'path'     => 'aggregateRating',
                'priority' => 150,
                'status'   => 'active',
            ],
        ],
    ],

    [
        'name'            => 'Collection Page Schema',
        'type'            => 'collection',
        'scope'           => 'collection',
        'status'          => 'active',
        'priority'        => 60,
        'override'        => 0,
        'replace_on_seed' => 1,

        'schema_json' => [
            '@context'    => 'https://schema.org',
            '@type'       => 'CollectionPage',
            '@id'         => '{{url}}#collection',
            'name'        => '{{title}}',
            'description' => '{{description}}',
            'url'         => '{{url}}',
            'isPartOf'    => [
                '@id' => '{{website_id}}',
            ],
            'publisher'   => [
                '@id' => '{{organization_id}}',
            ],
            'breadcrumb'  => [
                '@id' => '{{breadcrumb_id}}',
            ],
            'inLanguage'  => '{{language}}',
        ],

        'bindings' => [
            'title'           => 'title',
            'description'     => 'description',
            'url'             => 'url',
            'website_id'      => 'website_id',
            'organization_id' => 'organization_id',
            'breadcrumb_id'   => 'breadcrumb_id',
            'language'        => 'language',
        ],

        'conditions' => [
            [
                'data_key' => 'description',
                'field'    => 'description',
                'operator' => 'empty',
                'action'   => 'remove',
                'path'     => 'description',
                'priority' => 10,
                'status'   => 'active',
            ],
            [
                'data_key' => 'breadcrumb_id',
                'field'    => 'breadcrumb_id',
                'operator' => 'empty',
                'action'   => 'remove',
                'path'     => 'breadcrumb',
                'priority' => 20,
                'status'   => 'active',
            ],
            [
                'data_key' => 'language',
                'field'    => 'language',
                'operator' => 'empty',
                'action'   => 'remove',
                'path'     => 'inLanguage',
                'priority' => 30,
                'status'   => 'active',
            ],
        ],
    ],

    [
        'name'            => 'Product Category Collection Schema',
        'type'            => 'collection',
        'scope'           => 'product_category',
        'status'          => 'active',
        'priority'        => 62,
        'override'        => 0,
        'replace_on_seed' => 1,

        'schema_json' => [
            '@context'    => 'https://schema.org',
            '@type'       => 'CollectionPage',
            '@id'         => '{{url}}#collection',
            'name'        => '{{title}}',
            'description' => '{{description}}',
            'url'         => '{{url}}',
            'isPartOf'    => [
                '@id' => '{{website_id}}',
            ],
            'publisher'   => [
                '@id' => '{{organization_id}}',
            ],
            'breadcrumb'  => [
                '@id' => '{{breadcrumb_id}}',
            ],
            'inLanguage'  => '{{language}}',
        ],

        'bindings' => [
            'title'           => 'title',
            'description'     => 'description',
            'url'             => 'url',
            'website_id'      => 'website_id',
            'organization_id' => 'organization_id',
            'breadcrumb_id'   => 'breadcrumb_id',
            'language'        => 'language',
        ],

        'conditions' => [
            [
                'data_key' => 'description',
                'field'    => 'description',
                'operator' => 'empty',
                'action'   => 'remove',
                'path'     => 'description',
                'priority' => 10,
                'status'   => 'active',
            ],
            [
                'data_key' => 'language',
                'field'    => 'language',
                'operator' => 'empty',
                'action'   => 'remove',
                'path'     => 'inLanguage',
                'priority' => 20,
                'status'   => 'active',
            ],
        ],
    ],

    [
        'name'            => 'Breadcrumb Schema',
        'type'            => 'breadcrumb',
        'scope'           => 'global',
        'status'          => 'active',
        'priority'        => 50,
        'override'        => 0,
        'replace_on_seed' => 1,

        'schema_json' => [
            '@context'        => 'https://schema.org',
            '@type'           => 'BreadcrumbList',
            '@id'             => '{{breadcrumb_id}}',
            'itemListElement' => '{{breadcrumb_items}}',
        ],

        'bindings' => [
            'breadcrumb_id'    => 'breadcrumb_id',
            'breadcrumb_items' => 'breadcrumb_items',
        ],

        'conditions' => [
            [
                'data_key' => 'breadcrumb_items',
                'field'    => 'breadcrumb_items',
                'operator' => 'empty',
                'action'   => 'remove',
                'path'     => 'itemListElement',
                'priority' => 10,
                'status'   => 'active',
            ],
        ],
    ],

];
